import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { Actions } from "../store";

export default function Home() {
  const dispatch = useDispatch();
  const counter = useSelector((store) => store.counter.value);
  const users = useSelector((store) => store.network.users);

  const increment = () => dispatch(Actions.Counter.increment());
  const getUsers = () => dispatch(Actions.Network.getUsers());


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Counter: <a href="https://nextjs.org">{counter}</a>
        </h1>
        <button onClick={increment}>Increment</button>
        <button onClick={getUsers}>Get users</button>
        <h1 className={styles.title}>{JSON.stringify(users)}</h1>
      </main>
    </div>
  );
}
